doctrine:
    dbal:
        types:
            id: Notebook\Common\Infrastructure\Doctrine\Type\IdType

        default_connection: notebook
        connections:
            notebook:
                host: postgres
                port: 5432
                user: 'postgres'
                password: '%env(resolve:POSTGRES_PASSWORD)%'
                dbname: '%env(resolve:POSTGRES_DATABASE_NAME)%'
                driver: 'pdo_pgsql'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Note:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Note/Infrastructure/Resources/config/mapping'
                prefix: 'Notebook\Note\Domain'
